version: '3'

services:
  nginx:
    build: 
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - /home/shammouc/data/nginx:/etc/nginx/conf.d
    networks:
      - my_network

  wordpress:
    build:
      context: .
      dockerfile: ./requirements/wordpress/Dockerfile
    depends_on:
      - db
    ports:
      - "9000:80"
    volumes:
      - /home/shammouc/data/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpressdb
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspassword
    networks:
      - my_network

  db:
    build:
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspassword
    volumes:
      - /home/shammouc/data/mysql:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network:

