# Utiliser l'image WordPress comme image de base
FROM wordpress:latest

# Copier le fichier www.conf personnalisé pour PHP-FPM
COPY requirements/wordpress/conf/www.conf /usr/local/etc/php-fpm.d/www.conf

